### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by AlexEnrique** [AlexEnrique/UFABC-Chaos-project#2]
## TODO list

- [ ] Implement an algorithm to generate a bifucartion diagram.
  - [x] Make the bifucartion diagram of the logistic family.

- [x] Implement a function to study the stability of fixed points.

- [ ] Implement functions for periodic orbits.
  - [ ] Determine a way to deal with asymptotically periodic orbits.

- [ ] Think about how to get the Lyapunov number/exponent.

- [ ] Design a way to deal with **itineraries**

- [ ] Start to write the documentation

**Comment by AlexEnrique** [comment]
- [x] Exclude the `opCall()` method of the `Map(alias f)` class.

That method was used to have access to the aliased lambda. 
One way to get access to the lambda is to define a function template to capture the same alias as
```D
auto foo(alias f, ...)(Map!f map, ...) {
    \\ use 'f' here.
}
```

**Comment by AlexEnrique** [comment]
- [x] Start using a implemented function of the phobos or some library to get the derivative of the a function (e.g. in the `isSink()` and `isSource()` functions).

**Comment by AlexEnrique** [comment]
- [ ] Try using the following syntax to allow template alias with dynamic functions (e.g. with probabilistic iterated function system).

```D
map!(x => dynamicFunc(x))
```

- Is there an way to deal with run-time template values? 
  - Possibly Voldemort Types returned by templates?

**Comment by AlexEnrique** [comment]
> Is there an way to deal with run-time template values?
> * Possibly Voldemort Types returned by templates?

Yes! Look at this working example:
```D
auto createLogisticMap(double a, real x = real.init) {
    class _LogisticMap : Map!(x => a * x * (1 - x)) {
        this() {}

        this(real x) {
            super(x);
        }
    }

    if (x != real.init) return new _LogisticMap(x);
    return new _LogisticMap;
}

auto rnd = Mt19937_64(unpredictableSeed!ulong);
auto map = createLogisticMap(a, rnd.uniform01);
```

- [x] Implement it!

**Comment by AlexEnrique** [comment]
> ```d
> if (x != real.init) return new _LogisticMap(x);
>     return new _LogisticMap;
> ```

- The possibility to return a map without initialization asks for a kind of ```.setInitialValue()``` method of the ``` Map!(alias f) ``` class.
- [ ] Resolve this issue.

**Comment by AlexEnrique** [comment]
- [ ] Change the type of ```_orbit``` member variable to ```Appender!type```
